<a href="https://colab.research.google.com/github/Leee-Harin/13th_Seminar/blob/week04/4%E1%84%8C%E1%85%AE%E1%84%8E%E1%85%A1_%E1%84%80%E1%85%AA%E1%84%8C%E1%85%A6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 베이지안 최적화 기반 하이퍼 파라미터 튜닝 (w. HyperOpt)

In [ ]:
#pip install hyperopt

In [4]:
import hyperopt

print(hyperopt.__version__)

0.2.7

In [5]:
from hyperopt import hp

# -10 ~ 10까지 1간격을 가지는 입력 변수 x와 -15 ~ 15까지 1간격으로 입력 변수 y 설정.
search_space = {'x': hp.quniform('x', -10, 10, 1), 'y': hp.quniform('y', -15, 15, 1) } ### 빈칸

In [6]:
from hyperopt import STATUS_OK

# 목적 함수를 생성. 변숫값과 변수 검색 공간을 가지는 딕셔너리를 인자로 받고, 특정 값을 반환
def objective_func(search_space):
    x = search_space['x']
    y = search_space['y']
    retval = x**2 - 20*y

    return retval

In [7]:
from hyperopt import fmin, tpe, Trials
import numpy as np

# 입력 결괏값을 저장한 Trials 객체값 생성.
trial_val = Trials()

# 목적 함수의 최솟값을 반환하는 최적 입력 변숫값을 5번의 입력값 시도(max_evals=5)로 찾아냄.
best_01 = fmin(fn=objective_func, space=search_space, algo=tpe.suggest, max_evals=5
               , trials=trial_val, rstate=np.random.default_rng(seed=0))
print('best:', best_01)

100%|██████████| 5/5 [00:00<00:00, 644.82trial/s, best loss: -224.0]
best: {'x': np.float64(-4.0), 'y': np.float64(12.0)}

In [15]:
trial_val = Trials()

# max_evals를 20회로 늘려서 재테스트
best_02 = fmin(fn=objective_func, space=search_space, algo=tpe.suggest, max_evals=20
               , trials=trial_val, rstate=np.random.default_rng(seed=0))
print('best:', best_02)

100%|██████████| 20/20 [00:00<00:00, 564.72trial/s, best loss: -296.0]
best: {'x': np.float64(2.0), 'y': np.float64(15.0)}

### max_evals의 값을 조정해서 최적해인 x=0에 가깝게 다가가는 최소 시도 횟수를 찾아보세요! : 6

In [12]:
best_n = None
best_x_val = float('inf')  # |x| 최소값 추적

for n in range(1, 51):
    trial_val = Trials()
    best = fmin(fn=objective_func, space=search_space,
                algo=tpe.suggest, max_evals=n,
                trials=trial_val,
                rstate=np.random.default_rng(seed=0))

    x_val = abs(best['x'])

    if x_val < best_x_val:
        best_x_val = x_val
        best_n = n

print("최소 |x|:", best_x_val)
print("그때 시도 횟수:", best_n)

100%|██████████| 1/1 [00:00<00:00, 100.65trial/s, best loss: -64.0]
100%|██████████| 2/2 [00:00<00:00, 218.07trial/s, best loss: -184.0]
100%|██████████| 3/3 [00:00<00:00, 488.01trial/s, best loss: -184.0]
100%|██████████| 4/4 [00:00<00:00, 253.21trial/s, best loss: -224.0]
100%|██████████| 5/5 [00:00<00:00, 190.73trial/s, best loss: -224.0]
100%|██████████| 6/6 [00:00<00:00, 431.64trial/s, best loss: -296.0]
100%|██████████| 7/7 [00:00<00:00, 493.51trial/s, best loss: -296.0]
100%|██████████| 8/8 [00:00<00:00, 259.95trial/s, best loss: -296.0]
100%|██████████| 9/9 [00:00<00:00, 155.24trial/s, best loss: -296.0]
100%|██████████| 10/10 [00:00<00:00, 205.63trial/s, best loss: -296.0]
100%|██████████| 11/11 [00:00<00:00, 202.71trial/s, best loss: -296.0]
100%|██████████| 12/12 [00:00<00:00, 160.16trial/s, best loss: -296.0]
100%|██████████| 13/13 [00:00<00:00, 628.40trial/s, best loss: -296.0]
100%|██████████| 14/14 [00:00<00:00, 279.39trial/s, best loss: -296.0]
100%|██████████| 15/15 [00:00<00:00, 161.65trial/s, best loss: -296.0]
100%|██████████| 16/16 [00:00<00:00, 290.28trial/s, best loss: -296.0]
100%|██████████| 17/17 [00:00<00:00, 494.98trial/s, best loss: -296.0]
100%|██████████| 18/18 [00:00<00:00, 620.52trial/s, best loss: -296.0]
100%|██████████| 19/19 [00:00<00:00, 466.35trial/s, best loss: -296.0]
100%|██████████| 20/20 [00:00<00:00, 634.63trial/s, best loss: -296.0]
100%|██████████| 21/21 [00:00<00:00, 534.77trial/s, best loss: -296.0]
100%|██████████| 22/22 [00:00<00:00, 417.62trial/s, best loss: -296.0]
100%|██████████| 23/23 [00:00<00:00, 388.99trial/s, best loss: -296.0]
100%|██████████| 24/24 [00:00<00:00, 146.81trial/s, best loss: -296.0]
100%|██████████| 25/25 [00:00<00:00, 120.05trial/s, best loss: -296.0]
100%|██████████| 26/26 [00:00<00:00, 165.74trial/s, best loss: -296.0]
100%|██████████| 27/27 [00:00<00:00, 231.39trial/s, best loss: -296.0]
100%|██████████| 28/28 [00:00<00:00, 207.21trial/s, best loss: -296.0]
100%|██████████| 29/29 [00:00<00:00, 201.21trial/s, best loss: -296.0]
100%|██████████| 30/30 [00:00<00:00, 176.69trial/s, best loss: -296.0]
100%|██████████| 31/31 [00:00<00:00, 138.08trial/s, best loss: -296.0]
100%|██████████| 32/32 [00:00<00:00, 215.22trial/s, best loss: -296.0]
100%|██████████| 33/33 [00:00<00:00, 161.12trial/s, best loss: -296.0]
100%|██████████| 34/34 [00:00<00:00, 163.34trial/s, best loss: -296.0]
100%|██████████| 35/35 [00:00<00:00, 64.81trial/s, best loss: -296.0]
100%|██████████| 36/36 [00:00<00:00, 100.23trial/s, best loss: -296.0]
100%|██████████| 37/37 [00:00<00:00, 80.77trial/s, best loss: -296.0]
100%|██████████| 38/38 [00:00<00:00, 151.35trial/s, best loss: -296.0]
100%|██████████| 39/39 [00:00<00:00, 153.75trial/s, best loss: -296.0]
100%|██████████| 40/40 [00:00<00:00, 176.23trial/s, best loss: -296.0]
100%|██████████| 41/41 [00:00<00:00, 111.88trial/s, best loss: -296.0]
100%|██████████| 42/42 [00:00<00:00, 110.82trial/s, best loss: -296.0]
100%|██████████| 43/43 [00:00<00:00, 135.70trial/s, best loss: -296.0]
100%|██████████| 44/44 [00:00<00:00, 128.48trial/s, best loss: -296.0]
100%|██████████| 45/45 [00:00<00:00, 108.76trial/s, best loss: -296.0]
100%|██████████| 46/46 [00:00<00:00, 130.30trial/s, best loss: -296.0]
100%|██████████| 47/47 [00:00<00:00, 69.68trial/s, best loss: -296.0]
100%|██████████| 48/48 [00:00<00:00, 51.48trial/s, best loss: -296.0]
100%|██████████| 49/49 [00:00<00:00, 76.27trial/s, best loss: -296.0]
100%|██████████| 50/50 [00:00<00:00, 144.99trial/s, best loss: -296.0]
최소 |x|: 2.0
그때 시도 횟수: 6

### point : 명확한 답은 없지만, x=0(-0.0)에 근사하도록 여러분이 직접 값을 조정해보세요 :)

In [16]:
trial_val = Trials()

# max_evals의 값을 대입해서 최적해를 찾아보세요요
best_02 = fmin(fn=objective_func, space=search_space, algo=tpe.suggest, max_evals=6
               , trials=trial_val, rstate=np.random.default_rng(seed=0))
print('best:', best_02)

100%|██████████| 6/6 [00:00<00:00, 416.52trial/s, best loss: -296.0]
best: {'x': np.float64(2.0), 'y': np.float64(15.0)}

----------------------------------------------------------------------------

In [17]:
# fmin( )에 인자로 들어가는 Trials 객체의 result 속성에 파이썬 리스트로 목적 함수 반환값들이 저장됨
# 리스트 내부의 개별 원소는 {'loss':함수 반환값, 'status':반환 상태값} 와 같은 딕셔너리임.
print(trial_val.results)

[{'loss': -64.0, 'status': 'ok'}, {'loss': -184.0, 'status': 'ok'}, {'loss': 56.0, 'status': 'ok'}, {'loss': -224.0, 'status': 'ok'}, {'loss': 61.0, 'status': 'ok'}, {'loss': -296.0, 'status': 'ok'}]

In [18]:
# Trials 객체의 vals 속성에 {'입력변수명':개별 수행 시마다 입력된 값 리스트} 형태로 저장됨.
print(trial_val.vals)

{'x': [np.float64(-6.0), np.float64(-4.0), np.float64(4.0), np.float64(-4.0), np.float64(9.0), np.float64(2.0)], 'y': [np.float64(5.0), np.float64(10.0), np.float64(-2.0), np.float64(12.0), np.float64(1.0), np.float64(15.0)]}

In [19]:
import pandas as pd

# results에서 loss 키값에 해당하는 밸류들을 추출하여 list로 생성.
losses = [loss_dict['loss'] for loss_dict in trial_val.results]

# DataFrame으로 생성.
result_df = pd.DataFrame({'x': trial_val.vals['x'], 'y': trial_val.vals['y'], 'losses': losses})
result_df

     x     y  losses
0 -6.0   5.0   -64.0
1 -4.0  10.0  -184.0
2  4.0  -2.0    56.0
3 -4.0  12.0  -224.0
4  9.0   1.0    61.0
5  2.0  15.0  -296.0

### losses 값이 작을수록, 정확도가 최대화된다!

#스태킹 앙상블-유방암 데이터
*'##' 있는 데이 빈칸이 있습니다!

##tran,test 데이터 분리 스태킹

데이터 로드

In [20]:
import numpy as np
import pandas as pd

from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

cancer_data = load_breast_cancer()

#'data'와 'target' 합치기
pd.concat([pd.DataFrame(cancer_data.data, columns=cancer_data.feature_names), pd.DataFrame(cancer_data.target, columns=['target'])], axis=1)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1

테스트셋분리

In [21]:
X_data = cancer_data.data
y_label = cancer_data.target

X_train , X_test , y_train , y_test = train_test_split(X_data , y_label , test_size=0.2 , random_state=0)

개별모델,메타모델 객체 생성

In [22]:
from re import X
# 개별 ML 모델을 위한 Classifier 생성.
knn_clf  = KNeighborsClassifier(n_neighbors=4)
rf_clf = RandomForestClassifier(n_estimators=100, random_state=0)
dt_clf = DecisionTreeClassifier()
##Adaboost모델의 n_estimator는 결정트리의 개수를 의미하는 하이퍼파라미터입니다
##결정트리 개수를 100 으로 지정해주세요
ada_clf = AdaBoostClassifier(n_estimators=100)

# 최종 Stacking 모델을 위한 Classifier생성.
lr_final = LogisticRegression(C=10)

 개별 모델들을 학습

In [23]:
knn_clf.fit(X_train, y_train)
rf_clf.fit(X_train , y_train)
dt_clf.fit(X_train , y_train)
ada_clf.fit(X_train, y_train)

AdaBoostClassifier(n_estimators=100)

예측

In [24]:
# 학습된 개별 모델들이 각자 반환하는 예측 데이터 셋을 생성하고 개별 모델의 정확도 측정.
knn_pred = knn_clf.predict(X_test)
rf_pred = rf_clf.predict(X_test)
dt_pred = dt_clf.predict(X_test)
ada_pred = ada_clf.predict(X_test)

print('KNN 정확도: {0:.4f}'.format(accuracy_score(y_test, knn_pred)))
print('랜덤 포레스트 정확도: {0:.4f}'.format(accuracy_score(y_test, rf_pred)))
print('결정 트리 정확도: {0:.4f}'.format(accuracy_score(y_test, dt_pred)))
print('에이다부스트 정확도: {0:.4f} :'.format(accuracy_score(y_test, ada_pred)))

KNN 정확도: 0.9211
랜덤 포레스트 정확도: 0.9649
결정 트리 정확도: 0.9035
에이다부스트 정확도: 0.9737 :

In [25]:
##Q:제일 높은 정확도는?(수치를 쓰세요)
##A:0.9737

In [32]:
#모델별 예측값 세로로 합치기
##결정트리 예측값 입력
pred = np.array([knn_pred, rf_pred,dt_pred,ada_pred])
print(pred.shape)

# transpose를 이용해 행과 열의 위치 교환. 컬럼 레벨로 각 알고리즘의 예측 결과를 피처로 만듦.
pred = np.transpose(pred)
print(pred.shape)

(4, 114)
(114, 4)

In [33]:
lr_final.fit(pred, y_test)
final = lr_final.predict(pred)

print('최종 메타 모델의 예측 정확도: {0:.4f}'.format(accuracy_score(y_test , final)))

최종 메타 모델의 예측 정확도: 0.9825

## 교차검증 세트 기반의 스태킹

개별 기반 모델에서 최종 메타 모델이 사용할 학습 및 테스트용 데이터를 생성하기 위한 함수 작성

In [34]:
from sklearn.model_selection import KFold
from sklearn.metrics import mean_absolute_error

def get_stacking_base_datasets(model, X_train_n, y_train_n, X_test_n, n_folds ):
    # 지정된 n_folds값으로 KFold 생성.
    kf = KFold(n_splits=n_folds, shuffle=False)
    #추후에 메타 모델이 사용할 학습 데이터 반환을 위한 넘파이 배열 초기화
    train_fold_pred = np.zeros((X_train_n.shape[0] ,1 ))
    test_pred = np.zeros((X_test_n.shape[0],n_folds))
    print(model.__class__.__name__ , ' model 시작 ')

    for folder_counter , (train_index, valid_index) in enumerate(kf.split(X_train_n)):
        #입력된 학습 데이터에서 기반 모델이 학습/예측할 폴드 데이터 셋 추출
        print('\t 폴드 세트: ',folder_counter,' 시작 ')
        X_tr = X_train_n[train_index]
        y_tr = y_train_n[train_index]
        X_te = X_train_n[valid_index]

        #폴드 세트 내부에서 다시 만들어진 학습 데이터로 기반 모델의 학습 수행.
        model.fit(X_tr , y_tr)
        #폴드 세트 내부에서 다시 만들어진 검증 데이터로 기반 모델 예측 후 데이터 저장.
        train_fold_pred[valid_index, :] = model.predict(X_te).reshape(-1,1)
        #입력된 원본 테스트 데이터를 폴드 세트내 학습된 기반 모델에서 예측 후 데이터 저장.
        test_pred[:, folder_counter] = model.predict(X_test_n)

    # 폴드 세트 내에서 원본 테스트 데이터를 예측한 데이터를 평균하여 테스트 데이터로 생성
    test_pred_mean = np.mean(test_pred, axis=1).reshape(-1,1)

    #train_fold_pred는 최종 메타 모델이 사용하는 학습 데이터, test_pred_mean은 테스트 데이터
    return train_fold_pred , test_pred_mean

개별 모델별로 교차검증으로 데이터 학습

In [29]:
##7겹교차검증을 수행해주세요
knn_train, knn_test = get_stacking_base_datasets(knn_clf, X_train, y_train, X_test, 7)
rf_train, rf_test = get_stacking_base_datasets(rf_clf, X_train, y_train, X_test, 7)
dt_train, dt_test = get_stacking_base_datasets(dt_clf, X_train, y_train, X_test,  7)
ada_train, ada_test = get_stacking_base_datasets(ada_clf, X_train, y_train, X_test, 7)

KNeighborsClassifier  model 시작
	 폴드 세트:  0  시작
	 폴드 세트:  1  시작
	 폴드 세트:  2  시작
	 폴드 세트:  3  시작
	 폴드 세트:  4  시작
	 폴드 세트:  5  시작
	 폴드 세트:  6  시작
RandomForestClassifier  model 시작
	 폴드 세트:  0  시작
	 폴드 세트:  1  시작
	 폴드 세트:  2  시작
	 폴드 세트:  3  시작
	 폴드 세트:  4  시작
	 폴드 세트:  5  시작
	 폴드 세트:  6  시작
DecisionTreeClassifier  model 시작
	 폴드 세트:  0  시작
	 폴드 세트:  1  시작
	 폴드 세트:  2  시작
	 폴드 세트:  3  시작
	 폴드 세트:  4  시작
	 폴드 세트:  5  시작
	 폴드 세트:  6  시작
AdaBoostClassifier  model 시작
	 폴드 세트:  0  시작
	 폴드 세트:  1  시작
	 폴드 세트:  2  시작
	 폴드 세트:  3  시작
	 폴드 세트:  4  시작
	 폴드 세트:  5  시작
	 폴드 세트:  6  시작

개별 모델들의 예측값들을 합친 새로운 학습데이터 생성

In [30]:
Stack_final_X_train = np.concatenate((knn_train, rf_train, dt_train, ada_train), axis=1)
Stack_final_X_test = np.concatenate((knn_test, rf_test, dt_test, ada_test), axis=1)
print('원본 학습 피처 데이터 Shape:',X_train.shape, '원본 테스트 피처 Shape:',X_test.shape)
print('스태킹 학습 피처 데이터 Shape:', Stack_final_X_train.shape,
      '스태킹 테스트 피처 데이터 Shape:',Stack_final_X_test.shape)

원본 학습 피처 데이터 Shape: (455, 30) 원본 테스트 피처 Shape: (114, 30)
스태킹 학습 피처 데이터 Shape: (455, 4) 스태킹 테스트 피처 데이터 Shape: (114, 4)

In [31]:
lr_final.fit(Stack_final_X_train, y_train)
stack_final = lr_final.predict(Stack_final_X_test)

print('최종 메타 모델의 예측 정확도: {0:.4f}'.format(accuracy_score(y_test, stack_final)))

최종 메타 모델의 예측 정확도: 0.9649

#개별질문

In [37]:
##Q: 이번 1차 프로젝트에서 사용한(사용할) 모델과 그 모델을 선택한 이유를 설명해주세요
##A: 본 프로젝트에서는 가격 예측을 위해 Random Forest, Gradient Boosting, LightGBM, XGBoost 모델을 비교하였다.
##교차검증을 통한 성능 평가 결과, XGBoost 모델이 가장 높은 설명계수(R²)를 기록하여 최종 모델로 선정하였다.
##이는 XGBoost가 부스팅 기반 알고리즘으로서 비선형성과 변수 간 상호작용을 효과적으로 반영할 수 있기 때문이며, 다양한 특성을 가지는 숙소 데이터의 가격 패턴을 보다 잘 학습할 수 있다는 장점이 있다.