In [11]:
# 데이터 분석을 위한 판다스 라이브러리 불러오기
import pandas as pd
<<< import: 라이브러리를 불러오는 명령어
<<< pandas: 데이터 분석 라이브러리
<<< as pd: pandas를 pd라는 이름으로 사용
<<< 대부분의 판다스 코드는 pd.함수() 형태로 사용한다.

In [12]:
# 실습을 위한 학생 성적 데이터 생성
data = {
    "이름": ["철수", "영희", "민수", "지영", "수현"]
    "반": ["A", "A", "B", "B", "A"],
    "점수": [85, 90, 78, 92, 88]
}

# 데이터프레임 생성
df = pd.DataFrame(data)

# 데이터 확인
df
<<< 판다스에서는 표 형테 데이터를 DataFrame이라고 한다. pd.DataFrame: 표 형태 데이터 추출
<<< data: 딕셔너리 형태로 데이터 생성
<<< []: 데이터 값

   이름  나이  반  점수
0  철수  20  A  85
1  영희  22  A  90
2  민수  21  B  78
3  지영  23  B  92
4  수현  20  A  88

In [13]:
# 데이터의 기본 정보 확인
df.info()
<<< info() 함수: 데이터 정보, 컬럼(열) 개수, 데이터 타입, 결측값 여부 등을 제공한다.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      5 non-null      object
 1   나이      5 non-null      int64
 2   반       5 non-null      object
 3   점수      5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [14]:
# 데이터 상위 5개 확인
df.head()

   이름  나이  반  점수
0  철수  20  A  85
1  영희  22  A  90
2  민수  21  B  78
3  지영  23  B  92
4  수현  20  A  88

In [15]:
# 점수 열만 선택
df["점수"]
<<< 판다스에서 특정 열(Column)을 선택할 때는 DataFrmae["열이름"] 문법을 사용한다.

0    85
1    90
2    78
3    92
4    88
Name: 점수, dtype: int64

In [16]:
# 점수가 85점 이상인 학생 찾기
high_score = df[df["점수"] >= 85]

high_score

   이름  나이  반  점수
0  철수  20  A  85
1  영희  22  A  90
3  지영  23  B  92
4  수현  20  A  88

In [17]:
# 합격 여부 컬럼 생성 (80점 이상 합격)
df["합격여부"] = df["점수"] >= 80

df
<<< df[조건]

   이름  나이  반  점수   합격여부
0  철수  20  A  85   True
1  영희  22  A  90   True
2  민수  21  B  78  False
3  지영  23  B  92   True
4  수현  20  A  88   True

In [18]:
# 점수 평균 계산
average_score = df["점수"].mean()

average_score
<<< df["점수"] : 점수 열 선택
<<< .mean() : 평균 계산 함수

np.float64(86.6)

In [19]:
df["점수"].max()   # 최고 점수
df["점수"].min()   # 최저 점수
df["점수"].sum()   # 총합

np.int64(433)

In [20]:
# 점수를 기준으로 오름차순 정렬
df.sort_values("점수")

   이름  나이  반  점수   합격여부
2  민수  21  B  78  False
0  철수  20  A  85   True
4  수현  20  A  88   True
1  영희  22  A  90   True
3  지영  23  B  92   True

In [21]:
df.sort_values("점수", ascending=False)
<<< sort_values(): 데이터 정렬 함수
<<< "점수": 정렬 기준 열
<<< ascending = False: 내림차순 정렬

   이름  나이  반  점수   합격여부
3  지영  23  B  92   True
1  영희  22  A  90   True
4  수현  20  A  88   True
0  철수  20  A  85   True
2  민수  21  B  78  False

In [23]:
# 반별 평균 점수 계산
group_mean = df.groupby("반")["점수"].mean()

group_mean

반
A    87.666667
B    85.000000
Name: 점수, dtype: float64

In [24]:
# import pandas as pd

data = {
    "이름": ["철수","영희","민수","지영"],
    "점수": [85,90,78,92]
}

df = pd.DataFrame(data) <<< 데이터프레임 이름을 df로 설정 

df

   이름  점수
0  철수  85
1  영희  90
2  민수  78
3  지영  92

In [25]:
#1 점수 칼럼만 출력하시오.
df["점수"] 
<<< 판다스에서 열(Column)을 선택할 때 문법: Dataframe["열 이름"]
<<< 내가 만든 데이터프레임 이름: df
<<< 열 이름: 점수

0    85
1    90
2    78
3    92
Name: 점수, dtype: int64

In [27]:
#2 80점 이상 학생만 출력하시오.
df[df["점수"] >= 80]
<<< 판다스에서 조건 검색하는법: df[조건]

   이름  점수
0  철수  85
1  영희  90
3  지영  92

In [28]:
#3 평균 점수를 구하시오.
df["점수"].mean()
<<< 평균을 구하는 함수: .mean() 
    하지만 평균은 오직 숫자 데이터에서만 가능하므로 먼저 점수 열을 선택해야한다!!
<<< 리마인드) 통계 함수: mean() 평균 / sum() 합 / max() 최대 / min() 최소

np.float64(86.25)

In [29]:
#4 점수 기준으로 내림차순 정렬
df.sort_values("점수", ascending = False)
>>> 정렬 함수: sort_values()
>>> 내림차순 정리이므로 ascending = False

   이름  점수
3  지영  92
1  영희  90
0  철수  85
2  민수  78

In [30]:
#5 80점 이상이면 합격 열을 추가하시오.
df["합격"] = df["점수"] >= 80

df
<<< 판다스에서 새로운 열 만들기: df["새열"] = 값

   이름  점수     합격
0  철수  85   True
1  영희  90   True
2  민수  78  False
3  지영  92   True